name: spotify_playlist_scrubber
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  envied: ^0.5.1
  flutter:
    sdk: flutter
  palette_generator: ^0.3.3+3
  simple_logger: ^1.9.0+3
  spotify: ^0.12.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  envied_generator: ^0.5.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
